version: "3"

services:
  postgres:
    build:
      context: .
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME:-postgres}
    ports:
    - 5432:5432
    volumes:
    - "sql:/sql"

volumes:
  sql:
