version: "3"

services:
  postgres:
    build:
      context: .
    container_name: "fred-fdw"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
    - 5432:5432
    volumes:
    - "sql:/sql"

volumes:
  sql:
